### ISSUE TITLE
Emoji Not working.

### ISSUE THREAD

**Issue by attaullahpro** [iamBedant/OutlineTextView#7]
After using this library Emoji not showing in TextView.???

**Comment by rajsuvariya** [comment]
Hey @attaullahpro, Can you provide some more details like what have you tried what is the output?

**Comment by imattaullah** [comment]
Dear i mean when i use this library then these emoji like "😀 😁 😂 🤣 😃 😄" will not appear in TextView.

**Comment by rajsuvariya** [comment]
@attaullahpro Yes because, the current version of OutlineTextview is an extension of AppCompatTextView, not EmojiCompatTextView.
